"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden    = true
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900

[flavor]
use = "gruvbox"
